#!/bin/sh -ex
[ -d dist ] && rm -rf dist
sbt clean generateJs
mkdir -p dist
cp -RL site/ dist
if [ "$1" = "--s3" ]; then
    #aws s3 sync dist s3://ofairootohtaecashogh
    aws s3 sync dist s3://energysim.kooma.net
fi
echo "Finished!"
exit 0
